// This nodejs script generates the a static header file of timezones from IANA database. 
// It fetches json data from https://github.com/nayarsystems/posix_tz_db
// Usage: `node timezones_gen.js > Timezones.h`

const https = require('https');

const url = 'https://raw.githubusercontent.com/nayarsystems/posix_tz_db/master/zones.json';

const buildFile = (data) => {
  let names = "";
  let posix = "";
  const nameconsts = [];
  const posixconsts = [];
  const readables = [];

  const keys = Object.keys(data);

  keys.forEach((key, index) => {
    const readable = key.replace(/_/g, " ");
    readables.push(readable);
    names += `const char location${index}[] PROGMEM = "${readable}";\n`;
    posix += `const char posix${index}[] PROGMEM = "${data[key]}";\n`;
    nameconsts.push(`location${index}`);
    posixconsts.push(`posix${index}`);
  });

  let result = `
#include <Arduino.h>
  
// This file was generated by the script in tools/timezones_gen.js, 
// based on data found in https://github.com/nayarsystems/posix_tz_db

${names}

${posix}

const char * const location[] PROGMEM = {${nameconsts.join(",")}};
const char * const posix[] PROGMEM = {${posixconsts.join(",")}};
const char locationOptions[] PROGMEM = "data-controlledby='ntp_enabled' data-showon='1' data-options='${readables.join("|")}'";

  `;

  console.log(result);
};

https.get(url, (response) => {
  let body = '';

  response.on('data', function (chunk) {
    body += chunk;
  });

  response.on('end', function () {
    buildFile(JSON.parse(body));
  });
}).on('error', function (e) {
  console.error("Error fetching JSON file: ", e);
});